### ISSUE TITLE
A new geocoder for 2015

### ISSUE THREAD

**Issue by davidchiles** [Burning-Man-Earth/iBurn-Data#1]
I want to undertake writing a new geocoder for this year. In the past we've had a lot of hardcoded values and suspicious looking math.

### The plan so far
A simple geocoder that takes in values like `3:00 and Arcade`, `12:45 2100` or `9:00 plaza` and turns them into latitude and longitude values as best as possible. This should work for both art and camps.

I think it would be possible to use the same centerline streets that is used to generate the map tiles to generate all the information for the geocoder.

#### Todo
- [ ] Parse all formats of location strings
- [ ] New translation functions (playa coordinates to lat lon) using [Turf](https://github.com/Turfjs/turf).
- [ ] Derive data from streets geoJSON file
    - [ ] Get center point of city (aka intersection of 6:00, 9:00, 3:00)
    - [ ] Get bearing of the city (aka bearing of 6:00)
    - [ ] Extract city streets 
    - [ ] Extract special features like plazas

**Comment by chrisballinger** [comment]
I think William may have some of these algorithms already written but in an OpenOffice spreadsheet:
http://www.wkeller.net/BRC-GPS/2007/brc-gps.2007.ods

Are you thinking command line tool or single-page web app?

**Comment by davidchiles** [comment]
I'm thinking of a command line tool for now.

I think in the future it would be great if we could incorporate the work in the ods file into this process as well. So that the input would just be the parameters necessary to 'create' the city and everything is derived from that.

But for now I'll use the output from William, the [geo files](https://github.com/Burning-Man-Earth/iBurn-Data/tree/master/data/2014/geo), to do the geocoding.

**Comment by OnlyInAmerica** [comment]
If Turf sways you toward writing this as a Node application we can deploy it to [AWS Lambda](http://aws.amazon.com/lambda/). This might be a good fit since we're just hitting an API, processing the result, and depositing the result to S3.

The "command line tool" style would be right at home in that environment.
